### ISSUE TITLE
not working links in readme

### ISSUE THREAD

**Issue by N3rd10** [Mechanical-Advantage/AdvantageKit#104]
the non-working links are listed here
[What is AdvantageKit?](https://github.com/Mechanical-Advantage/AdvantageKit/blob/main/docs/WHAT-IS-ADVANTAGEKIT.md)
[online documentation](https://docs.advantagekit.org/)
[AdvantageKit example projects](https://github.com/Mechanical-Advantage/AdvantageKit/blob/main/docs/INSTALLATION.md#new-projects)

**Comment by jwbonner** [comment]
I fixed the links to "What is AdvantageKit?" and the example projects. The online documentation links appears to be working correctly.
