### ISSUE TITLE
Example Project Improvements

### ISSUE THREAD

**Issue by blaze-developer** [Mechanical-Advantage/AdvantageKit#109]
I think it would be quite helpful if there was an Advanced Swerve Skeleton that included support for onboard feedback and feedforward loops with TalonFX motors. This is essential for many teams in reducing latency, and I noticed that in your team's recent robot code, such onboard feedback loops are already implemented. Having something similar to that as well as with the new cleaned-up swerve code and constants in your recent robot repository would significantly improve the templates for swerve drive, making it easier for other teams to switch to this from large library swerves.

**Comment by jwbonner** [comment]
We are working on a number of major improvements to the swerve example projects for the 2025 beta, which already includes this change.

**Comment by blaze-developer** [comment]
Nice to hear :)

**Comment by tbowers7** [comment]
What is the expected 2025-beta release date?

**Comment by tbeadle** [comment]
I, too, am interested in how I can start playing around with the new AdvantageKit & example projects.

**Comment by tbowers7** [comment]
Yay!  Thanks!  https://github.com/Mechanical-Advantage/AdvantageKit/releases/tag/v4.0.0-beta-1
