### ISSUE TITLE
Adavantage kit not supporting ARM based processor in windows

### ISSUE THREAD

**Issue by Emma03L** [Mechanical-Advantage/AdvantageKit#111]
**Describe the bug**
Advantage kit seems to not support ARM based processors in windows.

**To Reproduce**
Build a gradle project with advanatageKit on windows with an ARM based processor.

**Screenshots**

**Version (required):**
 - OS: Windows 11
 - Project Information: WPILib version- 2024.3.2, Java version- 17

**Comment by jwbonner** [comment]
Are you trying to run code natively or through x86 emulation? WPILib doesn't distribute an installer for Windows on ARM, and I'm not aware of any vendors that distribute native artifacts for the platform. There shouldn't be a problem running WPILib and AdvantageKit in emulation, but I don't think we'll want to support Windows natively until WPILib does in the installer.

**Comment by Emma03L** [comment]
I'll run it through emulation, wasn't aware there isn't an ARM installer for windows. Thank you for the response!
