### ISSUE TITLE
Add support in `@AutoLogOutput` for `Trigger`s

### ISSUE THREAD

**Issue by katzuv** [Mechanical-Advantage/AdvantageKit#113]
The new command-based best practices suggest heavy usage of `Trigger`s to manage state. It'll be nice if we could use `@AutoLogOutput` on these.
Could probably use [`Trigger.getAsBoolean()`](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/wpilibj2/command/button/Trigger.html#getAsBoolean()), I just didn't understand myself how is `@AutoLogOutput` implemented.

**Comment by jwbonner** [comment]
More broadly, I think we could easily add support for output logging with supplier objects (`Trigger` inherits from `BooleanSupplier`).
