### ISSUE TITLE
Nested AutoLogged Classes

### ISSUE THREAD

**Issue by Mysterium422** [Mechanical-Advantage/AdvantageKit#116]
I think it would be nice to be able to nest AutoLogged Classes, so that I can I have a Subsystem IO that looks this:

```java
public class SubsystemIOInputs {
    public MotorIOInputsAutoLogged left = new MotorIOInputsAutoLogged();
    public MotorIOInputsAutoLogged right = new MotorIOInputsAutoLogged();
}
  ```

The implementation seems semi easy at first glace (hopefully im not missing something), you just add these two functions to LogTable.java:

```java
public <T extends LoggableInputs> void put(String key, T value) {
    if (value == null) return;
    value.toLog(getSubtable(key));
}

public <T extends LoggableInputs> T get(String key, T defaultValue) {
    if (defaultValue == null) return null;
    defaultValue.fromLog(getSubtable(key));
    return defaultValue;
}
```

But there seems to be potential for a recursion issue in that (although I definitely hope teams aren't trying to make recursive input classes). Thoughts?

**Comment by jwbonner** [comment]
This seems like a reasonable addition. To avoid crashing in the recursive case, we could probably add a counter for the number of subtable layers. Then if it gets too high (>100?), just print a warning and skip logging that set of inputs. I'm not really concerned about teams intentionally having recursive inputs, but the library should draw attention to the issue so it can be fixed.
