### ISSUE TITLE
Logging plain strings

### ISSUE THREAD

**Issue by jonahsnider** [Mechanical-Advantage/AdvantageKit#12]
In the future it would be nice if there was a way to log a plain string that would be stored in the RLOG file alongside all the other data, similar to how [WPILib's `DataLogManager#log`](https://first.wpi.edu/wpilib/allwpilib/docs/release/java/edu/wpi/first/wpilibj/DataLogManager.html#log(java.lang.String)) method works.

**Comment by jwbonner** [comment]
The 2023 beta release of AdvantageKit now automatically logs all text from STDOUT and STDERR to the "/RealOutputs/Console" field.
