### ISSUE TITLE
Incorrect Vendordep Link

### ISSUE THREAD

**Issue by blaze-developer** [Mechanical-Advantage/AdvantageKit#129]
On the existing projects tab on the docusaurus site, although it states that it is the instructions for the 2025 beta release, the Vendordep linked on that page redirects to version 3.2.1's JSON file.

**Comment by jwbonner** [comment]
While we are looking at ways to improve the distributing of the vendordep JSON (separate beta and stable streams, locking to a particular year, etc), we will not be making any changes for the 2025 season. The link will be correct after the 2025 kickoff release, and we will evaluate better options in 2026.
