### ISSUE TITLE
Multiple Limelight NT pose array indices are incorrect in the vision example project

### ISSUE THREAD

**Issue by ced4rtree** [Mechanical-Advantage/AdvantageKit#134]
**Describe the bug**
On [line 685 of LimelightHelpers.java](https://github.com/LimelightVision/limelightlib-wpijava/blob/main/LimelightHelpers.java#L685), you can see the index meant for values like tagCount and latency, which don't match the indices used in the vision example. For example, the vision project uses index 7 to get latency, which is used for tagCount in LimelightHelpers.java, and the vision project also uses index 8 for tagCount, which is used for tagSpan in LimelightHelpers.java. All the indices seem to be off by one. Did limelight add something to their spec after this was made or something?

**To Reproduce**
1. Collect data with a Limelight
2. Observe odd behavior in timestamps, tag count, ambiguity, tag IDs, tag distance.

**Expected behavior**
Timestamps behave perfectly linearly, tag count is non-zero at some point when the camera is certainly looking at a tag, ambiguity doesn't look like a distance value, tag IDs are reported, average tag distance goes beyond 1.2 meters.

**Screenshots**
![screenshot_20241219_025021](https://github.com/user-attachments/assets/49932d45-e1e5-475c-bf0b-3ae62f7533ce)
The timestamp can be clearly seen shifting on the scale of 1e-3

![screenshot_20241219_025915](https://github.com/user-attachments/assets/4b7201d9-fa1a-4f16-88c9-b665a9cb1c17)
Ambiguity is shifting as though it were distance to a tag

![screenshot_20241219_030036](https://github.com/user-attachments/assets/87ebf0b8-02ee-4db6-ae53-c0fddb9f44e3)
The tagCount of the right camera jumps up to 5 for but a single frame, but the pose observation having a non-zero x value demonstrates that the camera must have seen at least one tag for much longer

![screenshot_20241219_030632](https://github.com/user-attachments/assets/d496d36c-b4f1-4b67-8fa3-3a0003743d7a)
No tag poses are recorded throughout the test period, despite tags being in view. I believe this is because the tagID is fetched from index 10, which is used for area. The limelight docs don't say what unit this is in, just that it represents 0-100% of the camera area. If the percentage is reported as 0<=x<=1, then will always round down to zero, since it's very unlikely a tag will fill more than 50% camera real estate.

**Version (required):**
 - OS: Arch Linux 6.12.3-zen1-1-zen
 - Project Information:
 WPILib 2025.1.1-beta-2,
 Gradle 8.10.2, Java 17.0.12,
 AdvantageKit 4.0.0-beta-1,
 PathplannerLib 2025.0.0-beta-4
 Photonlib v2025.0.0-beta-5
 Phoenix6 2025.0.0-beta-3

**Additional context**
I've modified my code to match my robot and change some names, though it shouldn't change the fact the indices in the example project are different from those used in Limelight's library

**Comment by jwbonner** [comment]
Thanks for catching that. Limelight's documentation of the arrays is slightly inconsistent, but the LimelightHelpers class *should* be trustworthy. I pushed a fix for that.
