### ISSUE TITLE
Can't programmatically put LoggedDashboardChooser on shuffleboard

### ISSUE THREAD

**Issue by allengregoryiv** [Mechanical-Advantage/AdvantageKit#23]
When using LoggedDashboardChooser instead of sendableChooser, you can't currently send it directly to shuffleboard. If there was a method to get the sendableChooser from the class or some other way to put it on the shuffleboard page programmatically, that would be appreciated.

**Comment by jwbonner** [comment]
[v2.0.0-beta-2](https://github.com/Mechanical-Advantage/AdvantageKit/releases/tag/v2.0.0-beta-2) adds a `getSendableChooser()` method to `LoggedDashboardChooser`, so you can now call:

```java
Shuffleboard.getTab("Dashboard").add(loggedChooser.getSendableChooser());
```

Making the whole `LoggedDashboardChooser` object sendable is an ideal solution, but that's more difficult than expected. As long as you don't interact with the sendable chooser beyond putting it on a dashboard, this should work as a substitute.
