### ISSUE TITLE
Example configuration on install page doesn't work

### ISSUE THREAD

**Issue by jasondaming** [Mechanical-Advantage/AdvantageKit#24]
![image](https://user-images.githubusercontent.com/15695521/202928719-fbc67ddf-21a3-46da-bcdb-40241ad889f9.png)

This does both `Logger.getInstance` and uses `logger` which is presumably a previously assigned instance of the logger.  My suggestions would be:
1) Use one or the other.  If you choose to use `logger` then include the line that sets it.
2) `logger` of the `Logger` class can be confusing with both having the same name.

**Comment by jwbonner** [comment]
Thanks for pointing this out. I switched it to use `Logger.getInstance()` everywhere to avoid confusion with `logger` vs `Logger`
