### ISSUE TITLE
AutoLog generated files report compiler errors after being built

### ISSUE THREAD

**Issue by gcschmit** [Mechanical-Advantage/AdvantageKit#26]
We are trying the AutoLog annotation with AdvantageKit beta 2. The two files are being generated as expected and building the robot code completes successfully. However, after the build completes successfully, VS Code reports that these two files have compilation errors:

<img width="782" alt="Screen Shot 2022-12-12 at 9 10 59 AM" src="https://user-images.githubusercontent.com/1939236/207082227-11548acc-f2fb-4a0e-b77a-34da3f9222bc.png">

If I click on each file, the compilation error is immediately resolved as if VS Code realizes that the class is not already defined. This also presents itself when simulating the robot code as the build completes successfully but then, after selecting the simulator tool, VS Code reports that compilation fails. If I continue anyway, everything works as expected.

<img width="1174" alt="Screen Shot 2022-12-12 at 9 11 36 AM" src="https://user-images.githubusercontent.com/1939236/207082271-7c9e2b66-295b-40d0-96f5-c756dc524688.png">

We are using spotless, and we've excluded everything under generated-sources.

I'm running macOS 12.6.1 (arm64) and wpilib 2023.1.1-beta-6.

**Comment by jwbonner** [comment]
It seems like the simplest solution is to remove the section below from "build.gradle" that registers the generated classes with Gradle and VSCode. This doesn't appear to affect the Gradle build, but it stops VSCode from doing its (incorrect) error checking. The jump-to-definition function in VSCode still seems to still work properly.

```
sourceSets {
    main {
        java {
            srcDirs "src/main/java"
            srcDirs "build/generated/sources/annotationProcessor/java/main"
        }
    }
}
```

I’ve updated the docs and templates in 1115c65

**Comment by camearle20** [comment]
Note that not putting this in build.gradle in a new project will break VSCode from initially picking up generated sources. When you get compilation errors in VSCode with generated sources the only way I have found to fix it is to do "Clean Java Language Server Workspace" from the command palette. This seems to be an issue with the underlying, Eclipse based language server as this source set configuration shouldn't be necessary to begin with (for example IntelliJ IDEA properly picks up generated sources from a Gradle project with no configuration required).

I'm fine with leaving this out of our docs and seeing what happens, but I suspect this will trip up people who are creating new projects and expecting AutoLog to work properly.

**Comment by jwbonner** [comment]
I tried creating a new blank project without the "sourceSets", and VSCode seemed to pick up the generated sources correctly. The generated class appears in this "bin" folder that's only visible when the tab is open, but all of the functionality appears to be intact. Am I missing something?

<img width="515" src="https://user-images.githubusercontent.com/47046556/209448457-54cb1a2c-e3e1-44a7-93e4-5e0316db0191.png">

**Comment by camearle20** [comment]
It's quite possible that they updated the langauge server extension somehow and fixed this. I admittedly haven't actually tested this in a while. If this is working now without the build.gradle change then removing it is definitely the right call. Thanks for testing this!
