### ISSUE TITLE
Annotation Processor Dependency Problem

### ISSUE THREAD

**Issue by icemannie** [Mechanical-Advantage/AdvantageKit#29]
Adding the Annotation dependency won't allow a build.
2023 wpilib release

gradle.build as txt file

[build.txt](https://github.com/Mechanical-Advantage/AdvantageKit/files/10366420/build.txt)

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':annotationProcessor'.
   > Could not find org.littletonrobotics.akit.junction:junction-autolog:<version>.
     Searched in the following locations:
       - https://maven.pkg.github.com/Mechanical-Advantage/AdvantageKit/org/littletonrobotics/akit/junction/junction-autolog/<version>/junction-autolog-<version>.pom
       - file:/C:/Users/Public/wpilib/2023/maven/org/littletonrobotics/akit/junction/junction-autolog/<version>/junction-autolog-<version>.pom
       - https://repo.maven.apache.org/maven2/org/littletonrobotics/akit/junction/junction-autolog/<version>/junction-autolog-<version>.pom
     Required by:
         project :

**Comment by jwbonner** [comment]
You need to replace `<version>` with the latest version of AdvantageKit. For example:

```
annotationProcessor "org.littletonrobotics.akit.junction:junction-autolog:2.0.0"
```

**Comment by icemannie** [comment]
Thanks!
