### ISSUE TITLE
CAN usage high until inital enabled

### ISSUE THREAD

**Issue by itsmichaelyu** [Mechanical-Advantage/AdvantageKit#35]
![Screenshot 2023-02-18 at 4 20 22 PM](https://user-images.githubusercontent.com/64374317/219900117-331c20e8-fbbc-4011-87e7-e497ecd9c497.jpg)

We are facing really high loop run times when the robot is disabled. I'm thinking it could be something related to AdvantageKit, but it could totally be something on our end as well.

**Comment by jwbonner** [comment]
Could you send a log file where this occurs? You may need to put it in a zip file to upload to GitHub.

**Comment by itsmichaelyu** [comment]
[Feb18_Rattles.wpilog.zip](https://github.com/Mechanical-Advantage/AdvantageKit/files/10775228/Feb18_Rattles.wpilog.zip)

**Comment by jwbonner** [comment]
Based on the log, I don't think that this is an issue with AdvantageKit. Here's a graph with the periodic time for AdvantageKit (blue) and the user code (red). I also confirmed that the console capture is typically under a millisecond.

<img width="979" alt="Screen Shot 2023-02-18 at 4 35 54 PM" src="https://user-images.githubusercontent.com/47046556/219900499-a6b9b987-da69-4441-a48b-ebb009bfaa46.png">

**Comment by itsmichaelyu** [comment]
Yep, we found the problem. It was something we were calling in disabled periodic.
