### ISSUE TITLE
Simulator crashes if WPILOGWriter folder does not exist

### ISSUE THREAD

**Issue by mjansen4857** [Mechanical-Advantage/AdvantageKit#50]
When running the simulator, if you add a WPILOGWriter data receiver like so: 
```
Logger.addDataReceiver(new WPILOGWriter("logs"));
```
The code will crash if the folder `logs` does not exist. This is problematic because if we add all `.wpilog` files to `.gitignore`, the `logs` folder will not be tracked as it is empty. The code will then crash for anyone cloning the project until they manually create the `logs` folder.

The WPILOGWriter should create the specified folder if it does not exist.

**Comment by quizque** [comment]
Another thing to note: the crash has no error message, it simply exists which made this hard to realize what happened.
