### ISSUE TITLE
Support Enums in @AutoLogOutput

### ISSUE THREAD

**Issue by TylerSeiford** [Mechanical-Advantage/AdvantageKit#54]
We often use an `Enum` to define things like photon vision connection status or game piece held in an intake and it'd be nice to be able to automatically log them.  The current workaround is to manually log them with `Enum#name()`.

**Comment by jwbonner** [comment]
Thanks for the suggestion. In addition to `AutoLogOutput`, you can now use enums with `recordOutput` or as inputs with `AutoLog` and `LogTable`.
