### ISSUE TITLE
Add a link to AdvantageScope in the README

### ISSUE THREAD

**Issue by Gold872** [Mechanical-Advantage/AdvantageKit#56]
People often mixup AdvantageKit with AdvantageScope and vice versa. To help clear confusion people have, the README should have a clarification (difference between AKit and AScope) with a link to AdvantageScope in case if that's the repository they were looking for.

**Comment by jwbonner** [comment]
By coincidence, we were just recently having some internal discussions along these lines 😉. Thanks for the suggestion.

**Comment by jwbonner** [comment]
I added a similar note to the AdvantageScope README. WPILib data logging and NetworkTables are explained in other parts of the documentation (plus there are several other supported formats), so I didn't think it was necessary to copy over that piece of it.
