### ISSUE TITLE
Add support for two-dimensional arrays or Non-Loggable annotation

### ISSUE THREAD

**Issue by Jelatinone** [Mechanical-Advantage/AdvantageKit#97]
I noticed that `Logger#recordOutput(String, T...)` method does not apply to two-dimensional arrays, like below:

```java
Logger.recordOutput(("SuperPoopProperty"), new Transform2d[][] {});
```
This issue extends to classes which have been annotated using `@AutoLog`, in turn creating an issue where I am either forced to manually build out the generated class, or flatten the array into one-dimension (in turn loosing information).

**Is support for two-dimensional arrays with `Logger` possible to implement?**

If not, an alternative idea which I pointed out in #95 was the ability to apply some sort of `@DoNotLog` annotation which makes `@AutoLog` skip over the property during annotation processing.

**Comment by jwbonner** [comment]
Support for 2D arrays will be released in the 2025 beta.
